[build]
  base = "/"
  command = "pnpm build"
  publish = ".next"

[build.environment]
    NEXT_PUBLIC_SITE_URL = "https://horcrux.inc"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

[[redirects]]
  from = "/rob_shard.json"
  to = "/rob_shard.json"
  status = 200
